### ISSUE TITLE
Fatal error: Class 'phpCache\Factory' not found

### ISSUE THREAD

**Issue by mwcs01** [DzikuVx/WeatherStation#1]
Fatal error: Class 'phpCache\Factory' not found in /root/website/classes/General/Environment.php on line 41

**Comment by DzikuVx** [comment]
One of the dependecies has changed. As a temporary solution try this one:

```
cd website/classes/phpCache
git fetch
git checkout legacy
```

This should revert phpCache to previously used version on this library.

**Comment by DzikuVx** [comment]
current develop branch fixes the issue
