### ISSUE TITLE
Workaround for phpCache\Factory does not work

### ISSUE THREAD

**Issue by PieterGit** [DzikuVx/WeatherStation#2]
I get: 
Fatal error: Class 'phpCache\Factory' not found in /home/pi/WeatherStation/website/classes/General/Environment.php on line 41

Workaround
cd website/classes/phpCache
git fetch
git checkout legacy

So the workaround does not work:

pi@raspberrypi ~/xxx/WeatherStation/website/classes/phpCache $ git fetch
pi@raspberrypi ~/xxx/WeatherStation/website/classes/phpCache $ git checkout legacy
error: pathspec 'legacy' did not match any file(s) known to git.

Other questions:
1) Do you also get {"message":"Unauthorized.","cod":"401"}. when uploading to owm? See
https://openweathermap.desk.com/customer/portal/questions/12833018-no-weather-upload-possible

2) Would you be interested in patches to make it possible to use WeatherStation with an airbeam
( http://aircasting.org/ ) or Air Quality Egg V2 ( http://shop.wickeddevice.com/product/air-quality-egg-v2-no2-co/ )

**Comment by DzikuVx** [comment]
Try develop branch. It's not fully tested yet, but problem with phpCache\Factory should be solved

Questions:
1 - no, it works fine, no problems there
2 - no, there are no plans like that

**Comment by DzikuVx** [comment]
Current master solves the issue
